version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:6
    container_name: timetable_mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: timetable
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - timetable_network

  # Backend Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: timetable_backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/timetable?authSource=admin
      JWT_SECRET: your_super_secret_jwt_key_minimum_32_characters_long
      PORT: 5000
      FRONTEND_URL: http://localhost:3000
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - timetable_network
    volumes:
      - ./backend:/app
      - /app/node_modules

  # Frontend Service  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: timetable_frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - timetable_network
    environment:
      REACT_APP_API_URL: http://localhost:5000/api

volumes:
  mongodb_data:

networks:
  timetable_network:
    driver: bridge
